version: '2'
services:
  app:
    build: ./
    restart: always
    command: bash -c "python app.py data/nodos.txt data/arcos.txt 1"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    volumes:
      - ./:/src
